const TITLE_TEXT = 'Validity Options';
const ENTRY_EXIT_CODE_ENABLED_TEXT = 'Entry/Exit Point';
const DEPARTMENT_OFFICE_ENABLED_TEXT = 'Department Office';
const PLACE_OF_LOADING_ENABLED_TEXT = 'Place of Loading';
const PLACE_OF_UNLOADING_TEXT = 'Place of Unloading';
const TERM_OF_DELEVARY_ENABLED_TEXT = 'Term Of Delivery';
const INVOICE_VALUE_MANAGEMENT_ENABLED_TEXT = 'Invoice Value Management';
const LIST_OF_BENEFICIARIES_ENABLED = 'List Of Beneficiaries';
const HS_CODE_ENABLED = 'HS Code';

export default {
  TITLE_TEXT,
  ENTRY_EXIT_CODE_ENABLED_TEXT,
  DEPARTMENT_OFFICE_ENABLED_TEXT,
  PLACE_OF_LOADING_ENABLED_TEXT,
  PLACE_OF_UNLOADING_TEXT,
  TERM_OF_DELEVARY_ENABLED_TEXT,
  INVOICE_VALUE_MANAGEMENT_ENABLED_TEXT,
  LIST_OF_BENEFICIARIES_ENABLED,
  HS_CODE_ENABLED,
};
