const TITLE_TEXT = 'Validity Options';
const EXTEND_BEFORE_EXPIRATION_ENABLED_TEXT = 'Allow Extension Before End Of Validity';
const NUMBER_OF_DAYS_BEFORE_VALID_TO_TEXT = 'Number Of Days Before End Of Validity';
const NUMBER_OF_DAYS_BEFORE_VALID_TO_PLACEHOLDER = 'Number of days';
const EXTEND_AFTER_EXPIRATION_ENABLED_TEXT = 'Allow Extension After End Of Validity';
const NUMBER_OF_ALLOWABLE_EXTENTION_TEXT = 'Number of Allowable Extensions';
const NUMBER_OF_ALLOWABLE_EXTENTION_PLACEHOLDER = 'Number of Allowable Extention';
const MAX_NUM_OF_DAYS_FOR_EXTANTION_TEXT = 'Maximum Number of Days for Extension';
const MAX_NUM_OF_DAYS_FOR_EXTANTION_PLACEHOLDER = 'Maximum number of days';
const START_DATE_VALIDITY_TEXT = 'Validity Start Date';
const NUMBER_OF_DAYS_BEFORE_VALID_FROM_TEXT = 'Number of days';
const NUMBER_OF_DAYS_BEFORE_VALID_FROM_PLACEHOLDER = 'Maximum number of days';
const END_DATE_VALIDITY_TYPE_TEXT = 'Validity End Date';
const VALIDITY_PERIOD_TEXT = 'Validity Period';
const VALIDITY_PERIOD_PLACEHOLDER = 'Maximum number of days';

export default {
  TITLE_TEXT,
  EXTEND_BEFORE_EXPIRATION_ENABLED_TEXT,
  NUMBER_OF_DAYS_BEFORE_VALID_TO_TEXT,
  NUMBER_OF_DAYS_BEFORE_VALID_TO_PLACEHOLDER,
  EXTEND_AFTER_EXPIRATION_ENABLED_TEXT,
  NUMBER_OF_ALLOWABLE_EXTENTION_TEXT,
  NUMBER_OF_ALLOWABLE_EXTENTION_PLACEHOLDER,
  MAX_NUM_OF_DAYS_FOR_EXTANTION_TEXT,
  MAX_NUM_OF_DAYS_FOR_EXTANTION_PLACEHOLDER,
  START_DATE_VALIDITY_TEXT,
  NUMBER_OF_DAYS_BEFORE_VALID_FROM_TEXT,
  NUMBER_OF_DAYS_BEFORE_VALID_FROM_PLACEHOLDER,
  END_DATE_VALIDITY_TYPE_TEXT,
  VALIDITY_PERIOD_TEXT,
  VALIDITY_PERIOD_PLACEHOLDER,
};
