const TITLE_TEXT = 'Product Options';
const TARIFF_LIST_CODE_TEXT = 'Product List Code';
const TARIFF_LIST_CODE_PLACEHOLDER = 'Product Code';
const RELATED_PRODUCTS_ENABLED_TEXT = 'Show Related Products on License';
const RELATED_PRODUCTS = 'Related Products';
const RELATED_PRODUCTS_PLACEHOLDER = 'Related Products';

export default {
  TITLE_TEXT,
  TARIFF_LIST_CODE_TEXT,
  TARIFF_LIST_CODE_PLACEHOLDER,
  RELATED_PRODUCTS_ENABLED_TEXT,
  RELATED_PRODUCTS,
  RELATED_PRODUCTS_PLACEHOLDER,
};
