const OPERATION_NAME = 'Operation Name';
const OPERATION_NAME_IN_NL = 'Operation Name in NL';
const OPERATION_STATUS = 'Operation Status';
const OPERATION_STATUS_IN_NL = 'Operation Status in NL';
const OPERATION_RETURN = 'Return';
const OPERATION_RETURN_PLACEHOLDER = 'e.g. 1.1';
const OPERATION_CAN_REJECT = 'Can Reject';
const OPERATION_EDIT_BUTTON_TEXT = 'Edit';
const OPERATION_ADD_BUTTON_TEXT = 'Add';

export default {
  OPERATION_NAME,
  OPERATION_NAME_IN_NL,
  OPERATION_STATUS,
  OPERATION_STATUS_IN_NL,
  OPERATION_RETURN,
  OPERATION_RETURN_PLACEHOLDER,
  OPERATION_CAN_REJECT,
  OPERATION_EDIT_BUTTON_TEXT,
  OPERATION_ADD_BUTTON_TEXT,
};
