const TITLE_TEXT = 'Item Fields';
const PACKAGE_MANAGEMENT_ENABLED_TEXT = 'Package Management';
const ITEM_WEIGHT_MANAGEMENT_ENABLED_TEXT = 'Item Weight Management';
const PACKAGE_MANAGEMENT_TABLE_ENABLED_TEXT = 'Package Management Table';
const TREATMENT_TABLE_ENABLETEXT = 'Treatment Table';

export default {
  TITLE_TEXT,
  PACKAGE_MANAGEMENT_ENABLED_TEXT,
  ITEM_WEIGHT_MANAGEMENT_ENABLED_TEXT,
  PACKAGE_MANAGEMENT_TABLE_ENABLED_TEXT,
  TREATMENT_TABLE_ENABLETEXT,
};
